//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revista de Microbiologia
        ///Anais da Academia Brasileira de Ciências
        ///ACME
        ///Acta Dermato-Venereologica
        ///Acta Mycologica
        ///Acta Societatis Botanicorum Poloniae
        ///Acta Stomatologica Croatica
        ///Acta Veterinaria Brno
        ///Africa Spectrum
        ///Proceedings of NAS RA : Mechanics 
        ///Alfa: Revista de Lingüística
        ///Análise Social 
        ///Angle Orthodontist
        ///Archives Animal Breeding
        ///Archivo Español de Arte
        ///Archivos de Zootecnia
        ///Arquivos Brasileiros de Oftalmologia
        ///Arquivos de Gastroenterologia
        ///Arquivos de Neuro-Psiquiatria
        ///Ars Pharm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string doajlist {
            get {
                return ResourceManager.GetString("doajlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Review
        ///2D Materials
        ///3 Biotech
        ///3D Printing and Additive Manufacturing
        ///4OR-A Quarterly Journal of Operations Research
        ///AAPG BULLETIN
        ///AAPS Journal
        ///AAPS PHARMSCITECH
        ///AATCC Journal of Research
        ///AATCC REVIEW
        ///Abdominal Radiology
        ///ABHANDLUNGEN AUS DEM MATHEMATISCHEN SEMINAR DER UNIVERSITAT HAMBURG
        ///ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SOCIETY
        ///Academic Pediatrics
        ///Accountability in Research-Policies and Quality Assurance
        ///Acoustics Australia
        ///Acta Bioethica
        ///Acta Biomaterialia
        ///Acta Botanic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jcrlist {
            get {
                return ResourceManager.GetString("jcrlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Social Science
        ///
        ///Academic Exchange Quarterly
        ///Academic Research Reviews
        ///Academy of Contemporary Research Journal
        ///ACME Intellects
        ///Acta de Gerencia Ciencia
        ///Acta Advances in Agricultural Sciences
        ///Acta Kinesiologica
        ///Acta Medica International
        ///Acta Scientiae et Intellectus
        ///Acta Velit
        ///The Advance Journals of Engineering Mathematics and Computer Sciences
        ///Advance Research Journal of Multidisciplinary Discoveries
        ///The Advanced Science Journal
        ///Advances in Aerospace Science and Technology
        ///Advances in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string predatorylist {
            get {
                return ResourceManager.GetString("predatorylist", resourceCulture);
            }
        }
    }
}
